# Bundle defaults. Saved workspace and project preferences take precedence.
org.eventb.core/Interactive-Tactics\ Profil=Default Interactive Tactic with SMT
org.eventb.core/Auto-Tactics\ Profil=Default Auto Tactic with SMT
